config/routes.rb
Rails.application.routes.draw do
  resources :tweeets
  root 'tweeets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy

    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notification is-primary global-notification"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="notification is-primary global-notification"><%= alert %></p>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path,class:'navbar-item' do %>
          <h1>Twitter</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Tweet',new_tweeet_path,class:'button is-info is-inverted' %>
            </p>
            <p class="control">
              SignUp
            </p>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
	<article class="media box">
		<figure class="media-left">
			<p class="image	is-64x64">
				<img src="https://bulma.io/images/placeholders/64x64.png">
			</p>
		</figure>
		<div class="media-content">
			<%= render 'form',tweeet: @tweeet %>
		</div>
	</article>
</div>
<% @tweeets.each do |tweeet| %>
	<div class="box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64x64">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong>Diwakar Singh</strong><br/>
					<small>@diwakar</small><br/>
					<p><%= tweeet.tweeet %></p>
				</div>
				<nav class="level">
					<div class="level-left is-mobile">
						<%= link_to tweeet,class: "level-item" do %>
							<span class="icon">
								<%= fa_icon "link" %>
							</span>
						<% end %>
						<%= link_to edit_tweeet_path(tweeet),class:'level-item' do %>
							<span class="icon">
								<%= fa_icon "pencil" %>
							</span>
						<% end %>
						<%= link_to tweeet,method: :delete,data: {confirm: "Are you sure?"} do %>
							<span class="icon">
								<%= fa_icon "trash-o" %>
							</span>
						<% end %>
					</div>
				</nav>
			</div>
		</article>
	</div>
<% end %>

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet) do |form| %>
  <% if tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweeet %>
    <%= form.text_area :tweeet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeets/_trends.html.erb
<div class="cloumn is-one-quarter">
	<nav class="panel1">
		<p class="panel-heading">
			<a class="panel-block">
				Trend 1
			</a>
			<a class="panel-block">
				Trend 2
			</a>
			<a class="panel-block">
				Trend 3
			</a>
			<a class="panel-block">
				Trend 4
			</a>
			<a class="panel-block">
				Trend 5
			</a>
		</p>
	</nav>
</div>

app/views/tweeets/_who_to_follow.html.erb
<div class="cloumn">
	<nav class="panel1">
		<p class="panel1-heading">
			Who To Follow
		</p>
	</nav>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Sorcerer</strong>
						<small>@sorcerer</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Gods</strong>
						<small>@gods</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Cultivator</strong>
						<small>@cultivator</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Vastelorde</strong>
						<small>@vastelorde</small>
					</p>
				</div>
			</div>
		</article>
	</div>
</div>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'trends' %>
      <%= render 'feed' %>
      <%= render 'who_to_follow' %>
    </div>
  </div>
</section>

<p id="notice"><%= notice %></p>
<%= link_to 'New Tweeet', new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>